#!/usr/bin/env python
import sys
import os
import socket
import string

# CHANGE these two accordingly
TCP_PORT = 5005 
LOG_PATH = "/tg/tigergraph/logs/"

# gadmin command result won't be that long
BUFFER_SIZE = 100000
TCP_IP = '127.0.0.1'

SEC_PATH = os.path.join(LOG_PATH, ".tg_daemon.secret")
# now build the bricks
def validiate_cmd():
    allowed_cmds=[
            "start",
            "stop",
            "log",
            "status",
            "restart"]
    return "\n\t".join(allowed_cmds)

def get_secret():
    global SEC_PATH
    if os.path.isfile(SEC_PATH):
        with open(SEC_PATH) as fp:
            curren_secret = fp.readline()
        return curren_secret
    else:
        print "Failed to read secret from " + SEC_PATH
        return None

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print >>sys.stderr, 'Need provide one of the commands:'
        print >>sys.stderr, '\t', validiate_cmd()
        sys.exit(-2)
    secret = get_secret()
    if secret is not None:
        cmd = sys.argv
        cmd[0] = secret
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((TCP_IP, TCP_PORT))
        s.send(" ".join(cmd))
        data = s.recv(BUFFER_SIZE)
        s.close()
        print data
