apiVersion: graphdb.tigergraph.com/v1alpha1
kind: TigerGraphRestore
metadata:
  name: restore-from-s3
spec:
  restoreConfig:
    tag: s3-2023-08-23T060851 
    # optional
    stagingPath: /home/tigergraph/tigergraph/data/restore-staging
    # optional: (operator>=0.0.9 and tg>=3.9.3) should be >=0
    decompressProcessNumber: 2
  source:
    storage: s3Bucket 
    s3Bucket:
      # specify the bucket you want to use
      bucketName: operator-backup
      secretKeyName: aws-secret
  # Specify the name of cluster
  clusterName: test-cluster