{
 "title": "TigerGraph Dashboard",
 "description": "A comprehensive TigerGraph dashboard that visualizes key metrics collected directly from TigerGraph’s metrics endpoints. This dashboard provides insights into system performance, query execution, resource utilization, and other vital metrics, enabling effective monitoring and troubleshooting of TigerGraph deployments.",
 "tags": [ "tigergraph" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "ClusterName",
    "query": {
     "query": "label_values(tigergraph_cpu_usage{namespace=\"$Namespace\"},cluster_name)"
    }
   },
   {
    "name": "ServiceName",
    "query": {
     "query": "label_values(tigergraph_cpu_usage{namespace=\"$Namespace\", cluster_name=\"$ClusterName\"},service_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(tigergraph_cpu_usage{cluster_name=\"$ClusterName\",namespace=\"$Namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(tigergraph_service_status{service_name=~\"$ServiceName\",cluster_name=\"$ClusterName\",namespace=\"$Namespace\"}) by (service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Online Rate In The Past 10 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "clamp_max(avg(count_over_time((sum by (pod) (tigergraph_service_status{cluster_name=\"$ClusterName\",namespace=\"$Namespace\"}))[600s:])/on(pod) (count_over_time(kube_pod_container_info{pod=~\"${ClusterName}-.*\",container=\"tigergraph\"}[600s:])) * 100),100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(tigergraph_qps{cluster_name=\"$ClusterName\",namespace=\"$Namespace\",service_name=~\"RESTPP\"}) by (host_id, endpoint, service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(tigergraph_endpoint_latency{service_name=~\"RESTPP\", statistic=\"average_latency\",cluster_name=\"$ClusterName\",namespace=\"$Namespace\"}) by (host_id, service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\", container!=\"\"}[$__rate_interval])) by (container,pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(tigergraph_cpu_usage{service_name=~\"$ServiceName\",cluster_name=\"$ClusterName\",namespace=\"$Namespace\", pod=~\"$pod\"}) by (host_id, service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\", container!=\"\"}) by (container,pod)",
     "legendFormat": "{{pod}} {{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(tigergraph_memory_usage{service_name=~\"$ServiceName\",cluster_name=\"$ClusterName\",namespace=\"$Namespace\", pod=~\"$pod\"}) by (host_id, service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diskspace Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(tigergraph_diskspace_usage{pod=~\"$pod\",cluster_name=\"$ClusterName\",namespace=\"$Namespace\"}) by (host_id, path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  },
  {
   "title": "Network - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  }
 ]
}