FROM ubuntu:16.04

ENV DEV_VERSION 2.4.1
RUN useradd -ms /bin/bash tigergraph

RUN apt-get -qq update && apt-get install -y --no-install-recommends curl iproute2 net-tools cron ntp locales vim emacs wget git tar unzip jq uuid-runtime openssh-client openssh-server > /dev/null && \
  mkdir /var/run/sshd && \
  echo 'root:root' | chpasswd && \
  echo 'tigergraph:tigergraph' | chpasswd && \
  sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
  sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
  curl -s -L http://dl.tigergraph.com/developer-edition/tigergraph-2.4.1-developer.tar.gz \
    -o /home/tigergraph/tigergraph-dev.tar.gz && \
  cd /home/tigergraph/ && \
  tar xfz tigergraph-dev.tar.gz && \
  rm -f tigergraph-dev.tar.gz && \
  cd /home/tigergraph/tigergraph-* && \
  ./install.sh -n || : && \
  rm -fR /home/tigergraph/tigergraph-* && \
  rm -fR /home/tigergraph/tigergraph/dev/deploy_pkg && \
  rm -f /home/tigergraph/tigergraph/gium_prod.tar.gz && \
  rm -f /home/tigergraph/tigergraph/pkg_pool/tigergraph_*.tar.gz && \
  cd /tmp && curl -s -k -L "https://github.com/tigergraph/ecosys/archive/master.zip" -o /tmp/ecosys.zip && \
  unzip -q -o ecosys.zip && mv /tmp/ecosys-master/guru_scripts/docker/tutorial /home/tigergraph/tutorial && \
  curl -s -k -L "https://github.com/tigergraph/gsql-graph-algorithms/archive/master.zip" -o /tmp/algorithms.zip && \
  unzip -q -o algorithms.zip && mv /tmp/gsql-graph-algorithms-master /home/tigergraph/gsql-graph-algorithms && \
  rm -rf /tmp/* && \
  echo "export VISIBLE=now" >> /etc/profile && \
  echo "export USER=tigergraph" >> /home/tigergraph/.bash_tigergraph && \
  rm -f /home/tigergraph/.gsql_fcgi/RESTPP.socket.1 && \
  touch /home/tigergraph/.gsql_fcgi/RESTPP.socket.1 && \
  chmod 644 /home/tigergraph/.gsql_fcgi/RESTPP.socket.1 && \
  chown -R tigergraph:tigergraph /home/tigergraph && \
  su - tigergraph -c "/home/tigergraph/.gium/gadmin config-apply"

EXPOSE 22
ENTRYPOINT /usr/sbin/sshd && su - tigergraph bash -c "script -q /dev/null"
